package nl.marc_apps.weather.station_data

const val ANGLE_ZERO = 0
const val ANGLE_ONE_SIXTEENTH = 22_50
const val ANGLE_ONE_EIGHT = 45_00
const val ANGLE_THREE_SIXTEENTH = 67_50

const val ANGLE_A_QUARTER = 90_00
const val ANGLE_FIVE_SIXTEENTH = 112_50
const val ANGLE_THREE_EIGHTH = 135_00
const val ANGLE_SEVEN_SIXTEENTH = 157_50

const val ANGLE_A_HALF = 180_00
const val ANGLE_NINE_SIXTEENTH = 202_50
const val ANGLE_FIVE_EIGHTH = 225_00
const val ANGLE_ELEVEN_SIXTEENTH = 247_50

const val ANGLE_THREE_QUARTERS = 270_00
const val ANGLE_THIRTEEN_SIXTEENTH = 292_50
const val ANGLE_SEVEN_EIGHTH = 315_00
const val ANGLE_FIFTEEN_SIXTEENTH = 337_50

enum class WindDirection(val direction: Int) {
    N(ANGLE_ZERO),
    NNE(ANGLE_ONE_SIXTEENTH),
    NE(ANGLE_ONE_EIGHT),
    ENE(ANGLE_THREE_SIXTEENTH),
    E(ANGLE_A_QUARTER),
    ESE(ANGLE_FIVE_SIXTEENTH),
    SE(ANGLE_THREE_EIGHTH),
    SSE(ANGLE_SEVEN_SIXTEENTH),
    S(ANGLE_A_HALF),
    SSW(ANGLE_NINE_SIXTEENTH),
    SW(ANGLE_FIVE_EIGHTH),
    WSW(ANGLE_ELEVEN_SIXTEENTH),
    W(ANGLE_THREE_QUARTERS),
    WNW(ANGLE_THIRTEEN_SIXTEENTH),
    NW(ANGLE_SEVEN_EIGHTH),
    NNW(ANGLE_FIFTEEN_SIXTEENTH)
}

enum class WindDirectionDutch(val direction: Int) {
    N(ANGLE_ZERO),
    NNO(ANGLE_ONE_SIXTEENTH),
    NO(ANGLE_ONE_EIGHT),
    ONO(ANGLE_THREE_SIXTEENTH),
    O(ANGLE_A_QUARTER),
    OZO(ANGLE_FIVE_SIXTEENTH),
    ZO(ANGLE_THREE_EIGHTH),
    ZZO(ANGLE_SEVEN_SIXTEENTH),
    Z(ANGLE_A_HALF),
    ZZW(ANGLE_NINE_SIXTEENTH),
    ZW(ANGLE_FIVE_EIGHTH),
    WZW(ANGLE_ELEVEN_SIXTEENTH),
    W(ANGLE_THREE_QUARTERS),
    WNW(ANGLE_THIRTEEN_SIXTEENTH),
    NW(ANGLE_SEVEN_EIGHTH),
    NNW(ANGLE_FIFTEEN_SIXTEENTH)
}

val WindDirectionDutch.english: WindDirection
    get() = WindDirection.values().find { it.direction == this.direction }!!
