name: Static analysis with Detekt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Release tag associated with version of Detekt to be installed
  # SARIF support (required for this workflow) was introduced in Detekt v1.15.0
  DETEKT_RELEASE_TAG: v1.17.1

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Cache
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Permissions for Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Performs static analysis using Detekt
      - name: Run Detekt
        continue-on-error: true
        run: ./gradlew detekt

      # Uploads results to GitHub repository using the upload-sarif action
      - name: Publish results
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ${{ github.workspace }}/build/reports/detekt/detekt.sarif.json
          checkout_path: ${{ github.workspace }}
