name: Run and deployment

on:
  schedule:
    - cron: "5/20 6-19 * * *"
    - cron: "5 20-23,0-5 * * *"
  push:
    branches: [ main ]

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
    
      # Run
      - name: Run project
        run: ./bin/"Weather back-end" "out"
    
      # Deploy to GitHub Pages
      - name: Copy README, CNAME, etc.
        run: |
          sudo cp ./CNAME ./out/CNAME || echo "No CNAME"
          sudo cp ./README.md ./out/README.md || echo "No README.md"
          sudo cp ./LICENSE ./out/LICENSE || echo "No LICENSE"
    
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./out/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}