name: Run and deployment (*:03)

on:
  schedule:
    # Night: every 2 hours
    # Day: every hour
    # Evening: every hour and 20 minutes
    # 00:03, 02:03, 04:03, 05:23, 06:23, ..., 18:23, 19:23, 20:43, 22:03
    - cron: "3 0,2,4,22 * * *"
  workflow_dispatch:

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
    
      # Timestamp
      - name: Timestamp
        run: date
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: bin

      # Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Permissions for project
      - name: Grant execute permission for project
        run: chmod +x ./bin/WeatherBackend
    
      # Run
      - name: Run project
        run: ./bin/WeatherBackend "out"
    
      # Deploy to GitHub Pages
      - name: Copy README, CNAME, etc.
        run: |
          sudo cp ./CNAME ./out/CNAME || echo "No CNAME"
          sudo cp ./README.md ./out/README.md || echo "No README.md"
          sudo cp ./LICENSE ./out/LICENSE || echo "No LICENSE"
    
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./out/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
