name: Run and deployment

on:
  schedule:
    # Night: every 2 hours
    # Day: every 40 minutes
    # Evening: every 1 hour
    # 1:23 (+2h), 3:23 (+2h), 4:43, 5:23 (+40m), +40m ... 19:23 (+40m), 20:23 (+1h), 21:23 (+1h), 22:23 (+1h), 23:23 (+1h)
    - cron: "3,43 6-18/2 * * *"
    - cron: "43 4 * * *"
    - cron: "23 5-19/2 * * *"
    - cron: "23 1,3,20-23 * * *"
  workflow_dispatch:

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Permissions for project
      - name: Grant execute permission for project
        run: chmod +x ./bin/WeatherBackend
    
      # Run
      - name: Run project
        run: ./bin/WeatherBackend "out"
    
      # Deploy to GitHub Pages
      - name: Copy README, CNAME, etc.
        run: |
          sudo cp ./CNAME ./out/CNAME || echo "No CNAME"
          sudo cp ./README.md ./out/README.md || echo "No README.md"
          sudo cp ./LICENSE ./out/LICENSE || echo "No LICENSE"
    
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./out/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
